---
openapi: 3.0.3
info:
  title: User notes
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Yarik-osg/lab_5/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /user:
    post:
      tags:
      - User
      summary: Create new user to list
      description: Create new user to list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Invalid body supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  property_name:
                    type: string
                nullable: false
        "409":
          description: User with such email already exists
  /user/{userId}:
    get:
      tags:
      - User
      summary: Get user data
      description: Get user data
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Invalid Id supplied
        "404":
          description: User not found
    put:
      tags:
      - User
      summary: Edit user data
      description: Edit user data
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Invalid user supplied
        "404":
          description: user not found
    delete:
      tags:
      - User
      summary: Delete user
      description: Delete user
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: user has been deleted
        "400":
          description: Invalid user
        "404":
          description: user not found
  /user/{userId}/note:
    post:
      tags:
      - Note
      summary: Create new note
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "201":
          description: Create new note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/note'
        "400":
          description: Invalid body supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  property_name:
                    type: string
                nullable: false
  /user/{userId}/{noteId}:
    get:
      tags:
      - Note
      summary: Get notes data
      description: Get notes data
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/note'
        "400":
          description: Invalid Id supplied
        "404":
          description: User not found
    put:
      tags:
      - Note
      summary: Edit notes
      description: Edit notes
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/note'
        "400":
          description: Invalid Id supplied
        "404":
          description: Note not found
        "406":
          description: Not acceptable
    delete:
      tags:
      - Note
      summary: Delete notes
      description: Delete notes
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Note has been deleted
        "400":
          description: Invalid Note
        "404":
          description: Note not found
  /user/{noteId}/tag:
    post:
      tags:
      - Tag
      summary: Create new tag
      parameters:
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "201":
          description: Create new tag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tag'
        "400":
          description: Invalid body supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  property_name:
                    type: string
                nullable: false
  /user/{noteId}/{tagId}:
    get:
      tags:
      - Tag
      summary: Get tags
      description: Get tags data
      parameters:
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: tagId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tag'
        "400":
          description: Invalid Id supplied
        "404":
          description: Tag not found
    put:
      tags:
      - Tag
      summary: Edit tags
      description: Edit tags
      parameters:
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: tagId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tag'
        "400":
          description: Invalid Id supplied
        "404":
          description: tag not found
    delete:
      tags:
      - Tag
      summary: Delete tags
      description: Delete tags
      parameters:
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: tagId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Tag has been deleted
        "400":
          description: Invalid Tag
        "404":
          description: Tag not found
  /user/{noteId}/{historyId}/history:
    post:
      tags:
      - History
      summary: Create new history
      parameters:
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: historyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "201":
          description: Create new history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/history'
        "400":
          description: Invalid body supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  property_name:
                    type: string
                nullable: false
  /user/{userId}/{noteId}/{historyId}:
    get:
      tags:
      - History
      summary: Get history data
      description: Get history data
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: historyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/history'
        "400":
          description: Invalid history supplied
        "404":
          description: history not found
    put:
      tags:
      - History
      summary: Edit history
      description: Edit history
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: historyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/history'
        "400":
          description: Invalid history supplied
        "404":
          description: history not found
    delete:
      tags:
      - History
      summary: Delete history
      description: Delete history
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: noteId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: historyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: history has been deleted
        "400":
          description: Invalid history
        "404":
          description: history not found
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        name:
          type: string
        password:
          type: string
        email:
          type: string
          example: ex@mp.le
        stats_of_user:
          type: string
        count_of_messages:
          type: integer
          format: int32
      nullable: false
    note:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        count_of_users:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
    tag:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        name:
          type: string
        description:
          type: string
        id_note:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
    history:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        name:
          type: string
        description:
          type: string
        id_note:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        id_user:
          type: string
          format: uuid
          example: 3947539c-9c5c-45da-a2fe-62cc2f82f53d
        history_of_edit:
          type: string
        time_of_edit:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
