"""empty message

Revision ID: 8774a9b254d1
Revises: bad169bf5a18
Create Date: 2020-12-10 18:04:01.647753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8774a9b254d1'
down_revision = 'bad169bf5a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stats_user', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stats_user')
    # ### end Alembic commands ###
