"""empty message

Revision ID: 8c3c0d349cc2
Revises: 8774a9b254d1
Create Date: 2020-12-10 19:52:44.767305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3c0d349cc2'
down_revision = '8774a9b254d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_note', table_name='history')
    op.drop_index('id_users', table_name='history')
    op.drop_index('id_users', table_name='notes')
    op.drop_index('id_note', table_name='tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_note', 'tags', ['id_note'], unique=True)
    op.create_index('id_users', 'notes', ['id_users'], unique=True)
    op.create_index('id_users', 'history', ['id_users'], unique=True)
    op.create_index('id_note', 'history', ['id_note'], unique=True)
    # ### end Alembic commands ###
